### ISSUE TITLE
Possible to update to 2.92

### ISSUE THREAD

**Issue by gehan** [droboports/transmission#1]
How simple is it to update this when new versions of transmission are released?

If you say how you did it then I could have a go!

**Comment by ricardopadilha** [comment]
These are the things that need updating:
- [ ] Move to openssl 1.0.2g: https://github.com/droboports/transmission/blob/master/app.sh#L18
- [ ] Add the parallel build patch for openssl 1.0.2g here: https://github.com/droboports/transmission/tree/master/src
- [ ] Update to curl 7.47.1 here: https://github.com/droboports/transmission/blob/master/app.sh#L46
- [ ] Update the transmission 2.92 here: https://github.com/droboports/transmission/blob/master/app.sh#L81
- [ ] Update version number here: https://github.com/droboports/transmission/blob/master/src/dest/service.sh#L10
- [ ] Update version number here: https://github.com/droboports/transmission/blob/master/src/dest/www/includes/variables.php#L4
- [ ] Add some information here: https://github.com/droboports/transmission/blob/master/src/dest/www/includes/changelog.php

I think this mostly covers it.

**Comment by gehan** [comment]
I've done this and it works fine. I didn't update openssl as I didn't know where the parallel build patch was from.

https://github.com/droboports/transmission/pull/2

**Comment by ricardopadilha** [comment]
Thanks for the PR.

**Comment by d0cx** [comment]
Adding to this ticket, Transmission 2.92 no longer needs the "configure" option "--with-zlib={ARGUMENT}". While compiling, it gives a warning that there is no configure option for "--with-zlib". Check Transmission's source, it looks like they changed the way they included zlib, and it no longer requires calling it using the flag.
